import { useState, useEffect } from "react";

/**
 * useIsMobile hook. (generated by chat-gpt)
 * Returns true if the user agent is a mobile device.
 * @returns {boolean} True if the user agent is a mobile device.
 */

function useIsMobile(): boolean {
  const [isMobile, setIsMobile] = useState<boolean>(false);

  useEffect(() => {
    const userAgent: string =
      typeof window.navigator === "undefined" ? "" : window.navigator.userAgent;
    const isMobileAgent: boolean =
      /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        userAgent
      );

    setIsMobile(isMobileAgent);
  }, []);

  return isMobile;
}

export default useIsMobile;
