import { useState, useEffect } from "react";

/**
 * useWindowWidth hook. (generated by chat-gpt)
 * Returns the width of the window.
 * @returns {number} The width of the window.
 */

function useWindowWidth(): number {
  const [width, setWidth] = useState(0);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setWidth(window.innerWidth);

      const handleResize = (): void => {
        setWidth(window.innerWidth);
      };

      window.addEventListener("resize", handleResize);

      window.addEventListener("orientationchange", handleResize)

      return () => window.removeEventListener("resize", handleResize);
    }
  }, []);

  return width;
}

export default useWindowWidth;
